### PR TITLE
Revert back to just python stuff

### PR DESCRIPTION
**Pull request by npwalker**

### CODE REVIEW

**Comment by jarretlavallee** [comment]
Is *patch_files.rb* needed in this repo for pe < 3.8?

**Comment by reidmv** [comment]
@jarretlavallee `patch_files.rb` was only used to try and format the json files to make them compatible with the python visualizer. Since we aren't using that at all anymore, we shouldn't need `patch_files.rb`.

**Comment by npwalker** [comment]
I just went to the last commit from Chris and tried to make it match it looks like @reidmv added patch_files in the first non-chris commit.  If it should stick around I can put it back in.

**Comment by reidmv** [comment]
Yeah, let's leave `patch_files.rb` in place. That's pertinent to the python visualizer.

**Comment by npwalker** [comment]
okay patch_files.rb and it's part in the README are back.  If it's good, go ahead and merge it @reidmv

**Pull request merged**
