### PR TITLE
Add error metrics to the default dashboards

### PR DESCRIPTION
**Pull request by jarretlavallee**
Since correlation of error and performance data can be a telling sign of issues, this PR adds two graphs to both the performance and workload dashboards. The new graphs in the dashboards allow for the correlation of collection errors and performance data. This correlation may be useful when examining any highly taxed servers, or explain a gap in performance data within the dashboard. 

Each error is added individual metric in the servers.$server.<service>.error context with a hard coded 1 if present. Error counts are graphed as a separate adjacent graph. 

@npwalker This PR requires the merge of npwalker/pe_metric_curl_cron_jobs#13 as it ensures all errors are in an array for puppetserver. It may also be worth while to review the ruby code as ruby is quite new to me. 

**New Graphs (Bottom Row)**
New included graphs

**Use case for PuppetDB**
Potential PuppetDB graphs

### CODE REVIEW

**Comment by npwalker** [comment]
I'm +1.  @reidmv or @Sharpie thoughts?

**Comment by reidmv** [comment]
I like the metrics addition and having a dashboard. +1 for that!

I do think though that it would make more sense for this to be in its own dashboard, rather than duplicated into the performance and workload dashboards. The performance and workload dashboards can both be linked to the error dashboard, similarly to how the performance dashboard currently provides a one-way link to workload.

@jarretlavallee can we make that change, and then merge it?

Ruby code looks fine to me :)

**Comment by jarretlavallee** [comment]
I consolidated the error graphs into a new error dashboard. 
@reidmv Can you please confirm the new dashboard with data to ensure it is functioning as expected?

**Comment by reidmv** [comment]
@jarretlavallee I don't have data but if you do I can pair on it with you for 10 minutes. Ping me on HipChat!

**Comment by jarretlavallee** [comment]
@reidmv Updated with the changes we discussed. Please note that the links are now in the top left corner of the panel. Below is an image of the new dashboard with some test data. 

screen shot 2017-03-27 at 4 16 16 pm

**Pull request merged**
